All TF 2.0 model weights were used when initializing BertForMaskedLM.
Some weights of BertForMaskedLM were not initialized from the TF 2.0 model and are newly initialized: ['cls.predictions.decoder.weight', 'cls.predictions.decoder.bias', 'cls.predictions.decoder.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using DataParallel for NBmB
Training Loop:   0%|                                                                                                                                                                       | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/scratch1/yoonsoon/machine_translate/mBART_NepBERTa/finetuneNBmB.py", line 158, in <module>
    main()
  File "/scratch1/yoonsoon/machine_translate/mBART_NepBERTa/finetuneNBmB.py", line 149, in main
    finetune()
  File "/scratch1/yoonsoon/machine_translate/mBART_NepBERTa/finetuneNBmB.py", line 94, in finetune
    for batch in dataloader:
  File "/home1/yoonsoon/.conda/envs/startenv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home1/yoonsoon/.conda/envs/startenv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 678, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home1/yoonsoon/.conda/envs/startenv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home1/yoonsoon/.conda/envs/startenv/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 264, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home1/yoonsoon/.conda/envs/startenv/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 142, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home1/yoonsoon/.conda/envs/startenv/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 142, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home1/yoonsoon/.conda/envs/startenv/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 119, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home1/yoonsoon/.conda/envs/startenv/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 162, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [509] at entry 0 and [511] at entry 1